openapi: 3.0.3
info:
  title: Sports Infrastructure API
  description: API приложения интерактивной карты для размещения спортивной инфраструктуры
  version: 1.0.0
tags:
- name: objects
  description: Спортивные объекты
paths:
  /objects:
    post:
      tags:
        - objects
      summary: Получение списка объектов по фильтрам
      parameters:
        - in: query
          name: fromLat
          required: true
          description: Широта левого верхнего угла прямоугольника
          schema:
            type: integer
            example: 55.755819
        - in: query
          name: fromLng
          required: true
          description: Долгота левого верхнего угла прямоугольника
          schema:
            type: integer
            example: 37.617644
        - in: query
          name: toLat
          required: true
          description: Широта правого нижнего угла прямоугольника
          schema:
            type: integer
            example: 55.785819
        - in: query
          name: toLng
          required: true
          description: Долгота правого нижнего угла прямоугольника
          schema:
            type: integer
            example: 37.587644
      responses:
        200:
          description: Все параметры и фильтры корректны
  /population_density_heatmap:
    get:
      tags:
        - heatmap
      summary: Получение тепловой карты плотности населения
      parameters:
        - in: query
          name: minLat
          required: true
          description: Минимальная широта выделенной области
          schema:
            type: number
            example: 55.2
        - in: query
          name: minLng
          required: true
          description: Минимальная долгота выделенной области
          schema:
            type: number
            example: 36.9
        - in: query
          name: maxLat
          required: true
          description: Максимальная широта выделенной области
          schema:
            type: number
            example: 55.3
        - in: query
          name: maxLng
          required: true
          description: Максимальная долгота выделенной области
          schema:
            type: number
            example: 37.1
      responses:
        200:
          description: Границы области и матрица плотностей для этих границ
