openapi: 3.0.3
info:
  title: Sports Infrastructure API
  description: API приложения интерактивной карты для размещения спортивной инфраструктуры
  version: 1.0.0
tags:
- name: objects
  description: Спортивные объекты
paths:
  /objects:
    post:
      tags:
        - objects
      summary: Получение списка объектов по фильтрам
      parameters:
        - in: query
          name: fromLat
          required: true
          description: Широта левого верхнего угла прямоугольника
          schema:
            type: integer
            example: 55.755819
        - in: query
          name: fromLng
          required: true
          description: Долгота левого верхнего угла прямоугольника
          schema:
            type: integer
            example: 37.617644
        - in: query
          name: toLat
          required: true
          description: Широта правого нижнего угла прямоугольника
          schema:
            type: integer
            example: 55.785819
        - in: query
          name: toLng
          required: true
          description: Долгота правого нижнего угла прямоугольника
          schema:
            type: integer
            example: 37.587644
      responses:
        200:
          description: Все параметры и фильтры корректны