openapi: 3.0.3
info:
  title: Sports Infrastructure API
  description: API приложения интерактивной карты для размещения спортивной инфраструктуры
  version: 1.0.0
tags:
- name: objects
  description: Спортивные объекты
paths:
  /objects:
    post:
      tags:
        - objects
      summary: Получение списка объектов по фильтрам
      parameters:
        - in: query
          name: fromLat
          required: true
          description: Широта левого верхнего угла прямоугольника
          schema:
            type: number
            example: 55.755819
        - in: query
          name: fromLng
          required: true
          description: Долгота левого верхнего угла прямоугольника
          schema:
            type: number
            example: 37.587644
        - in: query
          name: toLat
          required: true
          description: Широта правого нижнего угла прямоугольника
          schema:
            type: number
            example: 55.785819
        - in: query
          name: toLng
          required: true
          description: Долгота правого нижнего угла прямоугольника
          schema:
            type: number
            example: 37.617644
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ObjectsFilters"
      responses:
        200:
          description: Все параметры и фильтры корректны
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Object"
  /objects/attributes:
    get:
      tags:
        - objects
      summary: Получение полной информации об объекте
      parameters:
        - in: query
          name: objectID
          required: true
          description: ID объекта
          schema:
            type: number
            example: 100153
      responses:
        200:
          description: Объект найден
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/ObjectExtended"
        404:
          description: Объект не найден
  /objects/filters:
    get:
      tags:
        - objects
      summary: Получение всевозможных фильтров
      responses:
        200:
          description: Все фильтры из базы данных получены
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      example: Департаменты
                    items:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                            example: 237332
                          name:
                            type: string
                            example: Департамент культуры города Москвы
  /heatmap/population-density:
    get:
      tags:
        - heatmap
      summary: Получение тепловой карты плотности населения
      parameters:
        - in: query
          name: minLat
          required: true
          description: Минимальная широта выделенной области
          schema:
            type: number
            example: 55.2
        - in: query
          name: minLng
          required: true
          description: Минимальная долгота выделенной области
          schema:
            type: number
            example: 36.9
        - in: query
          name: maxLat
          required: true
          description: Максимальная широта выделенной области
          schema:
            type: number
            example: 55.3
        - in: query
          name: maxLng
          required: true
          description: Максимальная долгота выделенной области
          schema:
            type: number
            example: 37.1
      responses:
        200:
          description: Границы области и матрица плотностей для этих границ
          content:
            application/json:
              schema:
                type: object
                properties:
                  geoRect:
                    description: Округленные вверх границы выделения
                    type: object
                    properties:
                      minLat:
                        type: number
                        example: 55.147199297273595
                      minLng:
                        type: number
                        example: 36.75571401201972
                      maxLat:
                        type: number
                        example: 56.078541702726405
                      maxLng:
                        type: number
                        example: 38.06930098798028
                  legend:
                    type: array
                    items:
                      type: object
                      properties:
                        minValue:
                          type: number
                          example: 6071.826484018266
                        maxValue:
                          type: number
                          example: 12143.652968036531
                        color:
                          type: number
                          example: 5740119
                  matrix:
                    description: Матрица плотностей
                    type: array
                    items:
                      type: array
                      items:
                        type: number
        400:
          description: Параметры некорректны
components:
  schemas:
    Object:
      description: Основные свойства спортивного объекта
      type: object
      properties:
        id:
          type: integer
          example: 100153
        name:
          type: string
          example: Дворовая территория
        lat:
          type: number
          description: Широта
          example: 55.49153457862329
        lng:
          type: number
          description: Долгота
          example: 37.30870755828658
        address:
          type: string
          example: город Троицк, улица Текстильщиков, дом 2А
    ObjectsFilters:
      description: Параметры фильтрации объектов
      type: object
      properties:
        objectName:
          type: string
          description: Название спортивного объекта
        departmentIds:
          type: array
          description: ID департаментов
          items: 
            type: integer
        sportzoneName:
          type: string
          description: Название спортивной зоны
        sportzoneTypesIds:
          type: array
          description: ID типов спортивных зон
          items:
            type: integer
        sportTypesIds:
          type: array
          description: ID видов спорта
          items:
            type: integer
        proximityIds:
          type: array
          description: ID возможных видов доступности
          items:
            type: integer
    ObjectExtended:
      description: Полная информация о спортивном объекте
      type: object
      properties:
        name:
          type: string
          example: Дворовая территория
        address:
          type: string
          example: город Троицк, улица Текстильщиков, дом 2А
        department:
          type: string
          description: Название департамента
          example: Департамент культуры города Москвы
        proximity:
          type: number
          description: Доступность объекта
          example: Шаговая доступность
        sportzones:
          type: array
          description: Список спортивных зон спортивного объекта
          items:
            type: object
            properties:
              name:
                type: string
                description: Название спортивной зоны
                example: зал спортивный
              square:
                type: number
                description: Площадь спортивной зоны
                example: 116.9
              sports_types:
                type: array
                items:
                  type: string
                  example: ["Баскетбол", "Волейбол"]
